"""add_progress_pct

Revision ID: 017079e9858d
Revises: b8876d12289f
Create Date: 2026-06-18 15:36:30.646667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017079e9858d'
down_revision: Union[str, None] = 'b8876d12289f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_jobs', sa.Column('progress_pct', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_jobs', 'progress_pct')
    # ### end Alembic commands ###
