"""add_contradicts_claim_id

Revision ID: 8725af5114d5
Revises: e4f447f5c3cf
Create Date: 2026-06-18 13:04:09.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8725af5114d5'
down_revision: Union[str, None] = 'e4f447f5c3cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claims', sa.Column('contradicts_claim_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'claims', 'claims', ['contradicts_claim_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'claims', type_='foreignkey')
    op.drop_column('claims', 'contradicts_claim_id')
    # ### end Alembic commands ###
