"""add_trust_score

Revision ID: 89d76d7fb51a
Revises: 017079e9858d
Create Date: 2026-06-18 16:32:32.778944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d76d7fb51a'
down_revision: Union[str, None] = '017079e9858d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('trust_score', sa.Integer(), nullable=True))
    op.add_column('sources', sa.Column('flags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'flags')
    op.drop_column('sources', 'trust_score')
    # ### end Alembic commands ###
