"""add_indexes_and_encrypt_webhook

Revision ID: b8876d12289f
Revises: fe3f61277437
Create Date: 2026-06-18 15:20:09.973760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8876d12289f'
down_revision: Union[str, None] = 'fe3f61277437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_research_jobs_created_at'), 'research_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_jobs_status'), 'research_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_sources_job_id'), 'sources', ['job_id'], unique=False)
    op.alter_column('webhook_endpoints', 'secret',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=False,
               postgresql_using='secret::bytea')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhook_endpoints', 'secret',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sources_job_id'), table_name='sources')
    op.drop_index(op.f('ix_research_jobs_status'), table_name='research_jobs')
    op.drop_index(op.f('ix_research_jobs_created_at'), table_name='research_jobs')
    # ### end Alembic commands ###
